// <auto-generated />
using BookStoreLite.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreLite.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreLite.DataAccess.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRare")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Author = "John Doe",
                            IsRare = false,
                            Price = 99.99m,
                            Title = "C# Fundamentals"
                        },
                        new
                        {
                            Id = 101,
                            Author = "Jane Smith",
                            IsRare = false,
                            Price = 129.50m,
                            Title = "ASP.NET Core in Action"
                        },
                        new
                        {
                            Id = 102,
                            Author = "Mark Johnson",
                            IsRare = false,
                            Price = 89.00m,
                            Title = "Entity Framework Core Guide"
                        },
                        new
                        {
                            Id = 103,
                            Author = "Emily Davis",
                            IsRare = false,
                            Price = 75.25m,
                            Title = "LINQ Deep Dive"
                        },
                        new
                        {
                            Id = 104,
                            Author = "Michael Brown",
                            IsRare = true,
                            Price = 150.00m,
                            Title = "Azure for Developers"
                        },
                        new
                        {
                            Id = 105,
                            Author = "Chris White",
                            IsRare = false,
                            Price = 110.00m,
                            Title = "Design Patterns in C#"
                        },
                        new
                        {
                            Id = 106,
                            Author = "Robert Martin",
                            IsRare = true,
                            Price = 140.00m,
                            Title = "Clean Code Practices"
                        },
                        new
                        {
                            Id = 107,
                            Author = "Anna Green",
                            IsRare = false,
                            Price = 120.00m,
                            Title = "Microservices with .NET"
                        },
                        new
                        {
                            Id = 108,
                            Author = "David Wilson",
                            IsRare = false,
                            Price = 95.00m,
                            Title = "Advanced SQL Server"
                        },
                        new
                        {
                            Id = 109,
                            Author = "Laura Taylor",
                            IsRare = false,
                            Price = 130.00m,
                            Title = "React and TypeScript"
                        },
                        new
                        {
                            Id = 110,
                            Author = "Peter Harris",
                            IsRare = false,
                            Price = 115.00m,
                            Title = "Angular Signals Explained"
                        },
                        new
                        {
                            Id = 111,
                            Author = "Sophia Clark",
                            IsRare = true,
                            Price = 160.00m,
                            Title = "OAuth 2.0 and PKCE"
                        },
                        new
                        {
                            Id = 112,
                            Author = "Daniel Lewis",
                            IsRare = false,
                            Price = 105.00m,
                            Title = "Minimal APIs in .NET"
                        },
                        new
                        {
                            Id = 113,
                            Author = "Olivia Walker",
                            IsRare = false,
                            Price = 80.00m,
                            Title = "JavaScript Essentials"
                        },
                        new
                        {
                            Id = 114,
                            Author = "James Hall",
                            IsRare = false,
                            Price = 95.00m,
                            Title = "TypeScript Best Practices"
                        },
                        new
                        {
                            Id = 115,
                            Author = "Grace Allen",
                            IsRare = true,
                            Price = 170.00m,
                            Title = "Cloud Security Basics"
                        },
                        new
                        {
                            Id = 116,
                            Author = "Henry Young",
                            IsRare = false,
                            Price = 90.00m,
                            Title = "EF Core Migrations"
                        },
                        new
                        {
                            Id = 117,
                            Author = "Isabella Scott",
                            IsRare = false,
                            Price = 100.00m,
                            Title = "SQL Collation & Unicode"
                        },
                        new
                        {
                            Id = 118,
                            Author = "Matthew King",
                            IsRare = false,
                            Price = 85.00m,
                            Title = "Postman & API Testing"
                        },
                        new
                        {
                            Id = 119,
                            Author = "Victoria Adams",
                            IsRare = true,
                            Price = 155.00m,
                            Title = "Secure File Handling in Azure"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
